# Base configs
baseurl: "https://gallery.lushuyu.site"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Lu Shuyu's gallery"
subtitle: "See the world through my eyes!"
author: "Lu Shuyu"
header:
 title: "Gallery"
 subtitle: "by Lu Shuyu"
footer:
 name: "Hey there, my name is Lu Shuyu"
 bio: "I am a student from China. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: ""
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/lushuyu"
